#	Make file for HW1 "Shahriyar Valielahi Roshan"
all:
		gcc	-o	multSimple	multSimple.c	-lrt	-lm
		gcc	-o	multBlocked	multBlocked.c	-lrt	-lm
		gcc -o  multBlockedV2 multBlockedV2.c -lrt  -lm
clean:
		rm	-f	multSimple multBlocked multBlockedV2
